feat: Check if user have any balance for rsk network and if they do use legacy coin type other way apply the new one
liquality/wallet pull request #191
Opened 2021-07-30 14:52 UTC by AndonMitev

…se legacy coin type other way apply the new one

2021-08-01 22:25 UTC, monokh requested changes
I'm worried about the scenario where the user receives some balance and the wallet has not updated for some reason. In that case, the user's wallet will be moved to new deriv path but they actually have a balance in the old deriv path. Is it possible to fetch the actual balance instead of just from the state? 
 you can see `updateBalances` for how to get balance

2021-08-01 22:25 UTC, monokh commented on src/store/migrations.js
> +      const accData = state.accounts[accKeys[0]].mainnet;
`accounts` is indexed by wallet id. I think you need to iterate over the walletIds and override rsk for each of them. See other migrations how to do this

2021-08-01 22:25 UTC, monokh commented on src/store/factory/client.js
> +  const derivationPath = `m/44'/${coinType}'/${indexPath}'/0/0`
Ledger wallet type should always use "legacy derivation"

2021-08-02 13:28 UTC, AndonMitev commented
> I'm worried about the scenario where the user receives some balance and the wallet has not updated for some reason. In that case, the user's wallet will be moved to new deriv path but they actually have a balance in the old deriv path. Is it possible to fetch the actual balance instead of just from the state?
> you can see `updateBalances` for how to get balance

All fixed

2021-08-03 10:24 UTC, monokh commented on src/store/actions/unlockWallet.js
> +  const accKeys = Object.keys(state.accounts);
You can call it "walletIds" 😄

2021-08-03 10:26 UTC, monokh commented on src/store/actions/unlockWallet.js
> +  for(let i = 0; i < accKeys.length; i++) {
this can be more readable in a foreach, either `for(const walletId in walletIds)` or `walletIds.forEach(walletId => {})`
same for below loop

2021-08-03 10:28 UTC, monokh commented on src/store/actions/unlockWallet.js
> +  const accKeys = Object.keys(state.accounts);
It might be nice to put this whole thing in a function like `getLegacyRskBalance(state.accounts)`

2021-08-03 10:29 UTC, monokh commented on src/store/migrations.js
> +      for(let i = 0; i < accKeys.length; i++) {
If you pull out the code in to a util function you can reuse it here

2021-08-03 12:43 UTC, bradleySuira approved these changes
LGTM

2021-08-04 08:19 UTC, monokh approved these changes

2021-08-04 08:20 UTC, merged