Feat/eip1559 custom fee
liquality/wallet pull request #399
Opened 2021-11-18 11:20 UTC by AndonMitev

#Linear Ticket

2022-01-06 20:52 UTC, beemi commented on src/components/CustomFeesEIP1559.vue
> +    minimum() {
extra space, lint issue

2022-01-06 20:53 UTC, beemi commented on src/components/CustomFeesEIP1559.vue
> +        )
extra space, lint issue

2022-01-06 20:55 UTC, beemi commented on src/components/CustomFeesEIP1559.vue
> +    maximum() {
space after function start, lint issue

2022-01-06 20:56 UTC, beemi approved these changes
please run `npm run lint`

2022-01-07 07:28 UTC, harshjv requested changes
Few comments;

1. To enable EIP1559, you need to pass `hardfork = 'london'` to JsWallet provider. You can change `createEthereumClient` and accept `hardfork` argument.
2. Fee provider needs to be added immediately after Rpc provider. Can you move `ethClient.addProvider(feeProvider)` below Rpc provider? https://github.com/liquality/wallet/blob/f3249c005e8ee3631917da351aa3a03f43a66c3f/src/store/factory/client.js#L129 below Rpc provider?
3. Polygon testnet supports EIP1559. Can you enable it here? https://github.com/liquality/wallet/blob/f3249c005e8ee3631917da351aa3a03f43a66c3f/src/store/factory/client.js#L206

2022-01-10 12:02 UTC, AndonMitev commented
> Few comments;
> 
> 1. To enable EIP1559, you need to pass `hardfork = 'london'` to JsWallet provider. You can change `createEthereumClient` and accept `hardfork` argument.
> 2. Fee provider needs to be added immediately after Rpc provider. Can you move `ethClient.addProvider(feeProvider)` below Rpc provider? https://github.com/liquality/wallet/blob/f3249c005e8ee3631917da351aa3a03f43a66c3f/src/store/factory/client.js#L129
>     below Rpc provider?
> 3. Polygon testnet supports EIP1559. Can you enable it here? https://github.com/liquality/wallet/blob/f3249c005e8ee3631917da351aa3a03f43a66c3f/src/store/factory/client.js#L206

done :)

2022-01-14 09:45 UTC, harshjv approved these changes
LGTM

2022-01-17 12:18 UTC, merged