Feat/blindex integration
liquality/wallet pull request #732
Opened 2022-03-31 14:19 UTC by MichalSzreder

2022-05-04 12:09 UTC, tima-t reviewed
LGTM

2022-05-10 13:19 UTC, tkeidar commented on test/e2e/import_wallet.spec.js
> +    const rskTokens = ['RBTC', 'SOV', 'FISH', 'BDX', 'BDUS', 'BDEU', 'XUSD', 'ETHs', 'bXAU', 'bGBP']
Add DOC

2022-05-10 13:22 UTC, tkeidar commented on test/pages/OverviewPage.js
> +      case 'BDX':
Add DOC

2022-05-10 13:22 UTC, tkeidar requested changes
add DOC on two spots

2022-05-11 08:52 UTC, MichalSzreder commented on test/e2e/import_wallet.spec.js
> +    const rskTokens = ['RBTC', 'SOV', 'FISH', 'BDX', 'BDUS', 'BDEU', 'XUSD', 'ETHs', 'bXAU', 'bGBP']
done

2022-05-11 08:52 UTC, MichalSzreder commented on test/pages/OverviewPage.js
> +      case 'BDX':
done

2022-05-17 11:47 UTC, tima-t reviewed
If possible, the icons could be in circles and follow our standard. 

We already have an icon for ETH so you can reuse it 

Beside that LGTM

2022-05-17 17:19 UTC, MichalSzreder commented
> If possible, the icons could be in circles and follow our standard.
> 
> We already have an icon for ETH so you can reuse it
> 
> Beside that LGTM

I have updated icons

2022-12-06 01:17 UTC, closed without merging