Automation tests for Hop
liquality/wallet pull request #790
Opened 2022-05-30 09:30 UTC by lydia-karungi

# :books: Linear Ticket :books:

2022-05-30 20:52 UTC, beemi requested changes

2022-05-30 20:52 UTC, beemi commented on .mocharc.yml
> +parallel: false
don't commit this file

2022-05-30 20:52 UTC, beemi commented on .gitignore
> +test/.env
?

2022-05-30 20:52 UTC, beemi commented on test/e2e/hop_tests/hop_swaps.spec.js
> +describe.only('SWAP feature["MAINNET"]', async () => {
.only

2022-05-31 08:18 UTC, lydia-karungi commented on .mocharc.yml
> +parallel: false
@beemi I have resolved this

2022-05-31 08:18 UTC, lydia-karungi commented on .gitignore
> +test/.env
@beemi Not sure what you mean here

2022-05-31 08:19 UTC, lydia-karungi commented on test/e2e/hop_tests/hop_swaps.spec.js
> +describe.only('SWAP feature["MAINNET"]', async () => {
@beemi this has been resolved

2022-05-31 12:51 UTC, merged