Automation tests for activity tab
liquality/wallet pull request #807
Opened 2022-06-13 09:09 UTC by lydia-karungi

# Check Export filter
#Check Date range & Type
# :books: Linear Ticket :books:

2022-06-14 13:46 UTC, beemi commented
@lydia-karungi  it would be good to write some tests to validate CSV data?
*  do any SEND
* then download CSV from activity
* Then validate the CSV data after downloaded

2022-06-17 13:14 UTC, lydia-karungi commented
> @lydia-karungi it would be good to write some tests to validate CSV data?
> 
> * do any SEND
> * then download CSV from activity
> * Then validate the CSV data after downloaded

@beemi All comments have been worked on, kindly review again

2022-06-20 09:33 UTC, beemi requested changes

2022-06-20 09:33 UTC, beemi commented on test/e2e/activity_page.spec.js
> +describe.only('Activity section["MAINNET"]', async () => {
can u remove .only

2022-06-20 09:33 UTC, beemi commented on test/e2e/activity_page.spec.js
> +
i think better to switch to testnet for this test

2022-06-21 12:07 UTC, beemi approved these changes

2022-06-21 12:07 UTC, merged